/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-container-high": "#ffe2dd",
        "surface-container-highest": "#ffdad4",
        "secondary-fixed": "#f7e28e",
        "primary-fixed-dim": "#fabd00",
        "surface-tint": "#785900",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#dac675",
        secondary: "#6c5e17",
        "on-primary-container": "#6d5100",
        "on-tertiary-fixed-variant": "#763300",
        "inverse-on-surface": "#ffedea",
        "surface-container": "#ffe9e5",
        "on-error-container": "#93000a",
        primary: "#785900",
        "surface-variant": "#ffdad4",
        background: "#fff8f6",
        "secondary-container": "#f4df8c",
        "surface-dim": "#f8d1cb",
        "surface-container-low": "#fff0ee",
        "on-tertiary-container": "#8c3e00",
        "inverse-primary": "#fabd00",
        "inverse-surface": "#422a26",
        "on-surface": "#2b1613",
        "on-tertiary": "#ffffff",
        tertiary: "#9b4500",
        "on-secondary-container": "#71621c",
        "tertiary-container": "#ffbc97",
        "on-surface-variant": "#4f4632",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#5b4300",
        "tertiary-fixed": "#ffdbc9",
        "surface-bright": "#fff8f6",
        "on-tertiary-fixed": "#331200",
        "outline-variant": "#d4c5ab",
        "primary-fixed": "#ffdf9e",
        "on-secondary-fixed": "#221b00",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#534600",
        "tertiary-fixed-dim": "#ffb68d",
        "on-background": "#2b1613",
        outline: "#827660",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#ffc107",
        "on-primary-fixed": "#261a00",
        surface: "#fff8f6"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        unit: "8px",
        "container-margin-mobile": "20px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        gutter: "16px",
        "container-margin-desktop": "64px",
        "stack-md": "16px"
      },
      fontFamily: {
        "body-lg": ["Quicksand"],
        display: ["Montserrat"],
        "label-sm": ["Quicksand"],
        "headline-lg": ["Montserrat"],
        "label-lg": ["Quicksand"],
        "body-md": ["Quicksand"],
        "headline-lg-mobile": ["Montserrat"],
        "headline-md": ["Montserrat"],
        headline: ["Montserrat"],
        body: ["Quicksand"],
        label: ["Quicksand"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "500" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
